# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- develop

pool:
  name: rookies-2022
  demands: npm

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: amo-admin
    verbose: false

- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: custom
    workingDir: amo-admin
    verbose: false
    customCommand: 'run build:prod'

# - task: ArchiveFiles@2
#   displayName: 'Archive files'
#   inputs:
#     rootFolderOrFile: amo-admin/build
#     includeRootFolder: false

- task: CopyFiles@2
  displayName: 'Copy files'
  inputs:
    SourceFolder: amo-admin/build
    TargetFolder: '$(build.artifactstagingdirectory)'
    
- task: CopyFiles@2
  displayName: 'Copy web.config'
  inputs:
    SourceFolder: amo-admin/web.config
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: CopyFiles@2
  displayName: 'Copy ARM templates'
  inputs:
    SourceFolder: ArmTemplates
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
